apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: argocd-examples
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/argoproj/argocd-example-apps
  ref:
    branch: master
