apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-index
  namespace: demo-app
data:
  index.html: |
    <title> Flux CD demo</title> Started by Flux CD. <p> special val = $(FLUX_var1:=standard)
    
